server.port=8503
spring.application.name=Comentarios

spirng.data.mongodb.uri=mongodb://localhost:27107/comentariosProyecto
spring.graphql.path=/comentarios
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

eureka.client.serviceUrl.defaultZone=https://localhost:8500/eureka
