server.port=8502

pring.datasource.url=jdbc:mysql://localhost:3306/usuariosproyecto
spring.datasource.username=root
spring.datasource.password=ricardoBD90-

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect